name       : nvidia-vaapi-driver
version    : 0.0.3
release    : 4
homepage   : https://github.com/elFarto/nvidia-vaapi-driver
source     :
    - git|https://github.com/elFarto/nvidia-vaapi-driver.git : 9b37fb11f7d6c88c66151e79527c5cb1be1a3502
license    : MIT
component  : xorg.display
summary    : A VA-API implemention using NVIDIA's NVDEC as the backend (UNSUPPORTED)
description: |
    This is an VA-API implementation that uses NVDEC as a backend. Mostly useful for firefox. (UNSUPPORTED)
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(ffnvcodec)
    - pkgconfig(gstreamer-codecparsers-1.0)
    - pkgconfig(libva)
    - nvidia-glx-driver-common
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
conflicts  :
    - libva-vdpau-driver
